FROM quay.io/koli/ubuntu:16.04

RUN adduser --system \
    --shell /bin/bash \
    --disabled-password \
    --no-create-home \
    --group k8smutator

USER k8smutator
COPY . /

ENTRYPOINT ["/usr/bin/k8smutator"]
